// Generated by CoffeeScript 1.6.3
var Database, deferred, instance, mysql;

mysql = require('mysql');

deferred = require('jquery-deferred').Deferred;

module.exports = Database = (function() {
  function Database() {
    this.connection = mysql.createConnection({
      host: 'localhost',
      user: 'root',
      password: 'dave',
      database: 'phonetica'
    });
  }

  Database.prototype.query = function(sql, attrs) {
    var _this = this;
    return deferred(function(defer) {
      var query;
      query = _this.connection.query(sql, attrs, function(err, result) {
        console.log(result ? "" + result.length + " records found" : err);
        if (err) {
          return defer.reject(err);
        } else {
          return defer.resolve(result);
        }
      });
      return console.log(query.sql);
    });
  };

  return Database;

})();

instance = null;

Database.Instance = function() {
  if (instance) {
    return instance;
  } else {
    return instance = new Database();
  }
};
