// Generated by CoffeeScript 1.6.3
var Database, deferred, dir, extn, list, squel, templateCache;

deferred = require('jquery-deferred').Deferred;

Database = require('../Database');

squel = require('squel');

extn = "hjs";

templateCache = {};

dir = ".";

list = function(req, res) {
  var sql;
  switch (req.params.id) {
    case 'languages':
      sql = squel.select().from('Languages').order('Name').toString();
      return Database.Instance().query(sql).done(function(result) {
        res.contentType('.js');
        console.log("list languages complete");
        return res.send(result);
      }).fail(function(err) {
        throw err;
      });
  }
};

module.exports = list;
