// Generated by CoffeeScript 1.6.3
var deferred, dir, extn, fs, hogan, template, templateCache;

deferred = require('jquery-deferred').Deferred;

fs = require('fs');

hogan = require('hogan.js');

extn = "hjs";

templateCache = {};

dir = ".";

template = function(req, res) {
  var fileName,
    _this = this;
  fileName = req.params.fileName.substr(0, req.params.fileName.lastIndexOf(".js"));
  return deferred(function(defer) {
    if (templateCache[fileName]) {
      return defer.resolve(templateCache[fileName]);
    } else {
      return fs.readFile("" + dir + "/partials/" + fileName + "." + extn, {
        encoding: 'utf8'
      }, function(err, file) {
        if (err) {
          defer.reject(err);
        } else {
          templateCache[fileName] = "define(['hogan'], function (Hogan) {\n	return new Hogan.Template(" + (hogan.compile(file, {
            asString: true
          })) + ");\n});";
        }
        return defer.resolve(templateCache[fileName]);
      });
    }
  }).done(function(tmpl) {
    res.contentType('.js');
    return res.send(tmpl);
  }).fail(function(err) {
    throw err;
  });
};

template.setDir = function(_dir) {
  return dir = _dir;
};

module.exports = template;
