// Generated by CoffeeScript 1.6.3
var Database, WordDAO, dao, deferred, squel, wordRoute;

deferred = require('jquery-deferred').Deferred;

Database = require('../Database');

WordDAO = require('../models/WordDAO');

squel = require('squel');

dao = new WordDAO();

wordRoute = function(req, res, next) {
  switch (req.params.verb) {
    case 'search':
      return dao.list(req.body.field, req.body.value).done(function(json) {
        return res.send(json);
      });
    case 'create':
      return dao.create(req.body).done(function(word) {
        res.contentType('.js');
        console.log("create word " + req.body.Roman + " complete. New ID=" + word.ID);
        return res.send(word);
      }).fail(function(err) {
        throw err;
      });
    case 'update':
      return dao.update(req.body).done(function(word) {
        res.contentType('.js');
        console.log("update word " + req.body.Roman + " complete");
        return res.send(word);
      }).fail(function(err) {
        throw err;
      });
    default:
      return next();
  }
};

module.exports = wordRoute;
