// Generated by CoffeeScript 1.6.3
var Database, WordListModel;

Database = require('../Database');

module.exports = WordListModel = (function() {
  function WordListModel() {}

  WordListModel.prototype.create = function() {};

  WordListModel.prototype.get = function() {};

  WordListModel.prototype.update = function() {};

  WordListModel.prototype.remove = function() {};

  WordListModel.prototype.list = function(text) {
    var sql;
    sql = "SELECT *, levenshtein(LOWER(Roman), LOWER('" + text + "')) AS Dist FROM Words				WHERE levenshtein(LOWER(Roman), LOWER('" + text + "')) < CHAR_LENGTH('" + text + "')				ORDER BY Dist LIMIT 100";
    return Database.Instance().query(sql);
  };

  return WordListModel;

})();
