// Generated by CoffeeScript 1.6.3
var Database, WordListModel, squel;

Database = require('../Database');

squel = require('squel');

module.exports = WordListModel = (function() {
  function WordListModel() {}

  WordListModel.prototype.create = function() {};

  WordListModel.prototype.get = function() {};

  WordListModel.prototype.update = function() {};

  WordListModel.prototype.remove = function() {};

  WordListModel.prototype.list = function(field, value) {
    var sql;
    sql = squel.select().from('Words').field('ID').field('Roman').field('Native').field('Phonetic').field('Languages').field("levenshtein(LOWER(Roman), LOWER('" + value + "')) AS Dist").where("levenshtein(LOWER(Roman), LOWER('" + value + "')) < CHAR_LENGTH('" + value + "')").order('Dist').limit(100).toString();
    return Database.Instance().query(sql);
  };

  return WordListModel;

})();
